### ISSUE TITLE
Toolchain Build Issue

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/swift#108]
Even though I can build Swift for TF successfully on my mac, I cannot build the toolchain when using the following command:

```
$ ./utils/build-toolchain-tensorflow $BUNDLE_PREFIX
```

I get the following error:

```
Undefined symbols for architecture x86_64:
  "lldb_private::SwiftCompleteCode(swift::SourceFile&, llvm::StringRef)", referenced from:
      lldb_private::SwiftLanguage::CompleteCode(lldb_private::Target&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in liblldb-core.a(SwiftLanguage.o)
  "lldb::SBCompletionResponse::SBCompletionResponse(lldb_private::CompletionResponse const*)", referenced from:
      lldb::SBTarget::CompleteCode(lldb::LanguageType, lldb::SBSymbolContext const*, char const*) in SBTarget.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
        Ld /.../swift-source/build/buildbot_osx/lldb-macosx-x86_64/CustomSwift-Release/LLDB.framework/Versions/A/LLDB normal x86_64
(1 failure)
./utils/build-script: fatal error: command terminated with a non-zero exit status 65, aborting
./utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
```

Is there an easy fix for this or is it also related to the outdated Mac toolchain in the installation instructions?

Thanks!

**Comment by rxwei** [comment]
cc @marcrasi

**Comment by marcrasi** [comment]
I'm pretty sure that this is caused by https://github.com/apple/swift-lldb/pull/1269, because those are some symbols that I added in new files in that PR. I added these files to the CMakeLists.txt in that PR, but I am guessing that Mac doesn't use CMakeLists.txt?

What does it use? That probably needs to be updated.

**Comment by ewconnell** [comment]
I had a successful toolchain build this morning on ubuntu. I did an
update-checkout and then

$ ./utils/build-toolchain-tensorflow --gpu

I am using it now, Ed

**Comment by marcrasi** [comment]
I should be able to push out a fix in an ~hour. In the meantime, checking out commit 27187c73b243fb8f06dd62b35b82d4aad48161e6 in `lldb/` should let you compile.

**Comment by marcrasi** [comment]
This should be fixed now.

https://github.com/apple/swift-lldb/commit/84d14c9d5b145c8af30b5cb740ab41ba2ec35f28 fixes LLDB, and https://github.com/apple/swift/commit/d2f10a0189f9a418fcc1c89a5d1367051bf2e25f updates the Swift repo to point at the commit that fixed LLDB.

**Comment by eaplatanios** [comment]
Thanks @marcrasi! I just tested and it compiles fine now :)
